### PR TITLE
chore: Fix sonar analysis steps in pnp workflows

### PR DESCRIPTION
**Pull request by nadiiaboichuk**
Got the following message from Samuel:
> Looks like you’re using sonar incorrectly.
```
- name: Analyze with Sonar  
        uses: extenda/actions/sonar-scanner@v0
        with:
          sonar-host: https://sonarcloud.io/
          sonar-scanner: dotnet
          main-branch: ${{ steps.semver.outputs.branch-name-short }}
          service-account-key: ${{ secrets.SECRET_AUTH }}
```
> I think the main-branch argument as defined here will change the main to point to the current PR. This will mess up your quality gates. The main branch should be a static value, typically master unless a gitflow workflow is used when develop is main.
> Could you try to change this and see if your coverage still works as you expect? Right now I’m worried you don’t really have a long term quality gate.

### CODE REVIEW

**Comment by nadiiaboichuk** [comment]
Tested in Print Schedule and Price Specification Query APIs:
- https://github.com/extenda/hiiretail-price-specification-query-api/pull/167
- https://github.com/extenda/hiiretail-print-schedule-query-api/pull/36

**Comment by nadiiaboichuk** [comment]
Can in be done together with https://github.com/extenda/shared-workflows/pull/46 since you will be updating all the repos with new workflow versions?

**Comment by OUeland** [comment]
> @OUeland , I have one more change to our shared workflow. Can it be done together with #46 since you will be updating all the repos with new workflow versions?

Yes, it can! Although I am not sure when I will manage to do all the updates...

**Comment by abednii** [comment]
@nadiiaboichuk Are you sure it main-branch should be removed everywhere and not be set to " main-branch: master"? At least that's how I read message from Samuel

**Comment by nadiiaboichuk** [comment]
`master` is the default value for `main-branch` according to [action.yaml](https://github.com/extenda/actions/blob/master/sonar-scanner/action.yml), so we don't need to set it explicitly.

**Comment by abednii** [comment]
I'd say it's ok to go either way. We can merge two PRs and have two versions, no problem with that. Just need to ensure we use latest one, with both changes included, when starting modifying workflows in our services. I'll approve this one, so we'd have flexibility

**Review by OUeland — APPROVED** [review]

**Pull request merged**
