### PR TITLE
feat(MCPE-4149): Add a new S&G pipeline flag "release-to-staging-only"

### PR DESCRIPTION
**Pull request by pavel-dolinski**

### CODE REVIEW

**Review by ivolcov — APPROVED** [review]
I would suggest referencing the modified workflow from this branch in the new service to make sure it works.

**Comment by ivolcov** [comment]
And I'm not entirely sure if it's a good idea to modify other workflows and composite-actions. These changes might cause unexpected consequences and affect other products.

**Comment by pavel-dolinski** [comment]
> I would suggest referencing the modified workflow from this branch in the new service to make sure it works.

We cannot test the new pipeline parameter in `scanngo-selfscan` (we must be sure that it works properly before we will use it there), so I was going to test the new parameter in `scanngo-recovery` first.

**Comment by pavel-dolinski** [comment]
> And I'm not entirely sure if it's a good idea to modify other workflows and composite-actions. These changes might cause unexpected consequences and affect other products.

I have committed only those changes which should be safe (i.e. where the new versions of the standard actions a fully compatible with the currently used ones and to not have any breaking changes).

**Pull request merged**
